# Generated by Django 5.0.2 on 2024-03-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortSnip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(max_length=15),
        ),
    ]
